-- Seed catalogue for Floci Flix: 150 films, each a distributed-systems failure
-- mode with a plot.
--
-- Runs once, only when the movies table is empty (see App.seed). ON CONFLICT
-- makes it safe to run again anyway: re-running must never resurrect a row
-- somebody deleted, nor fail the app's startup.
--
-- PostgreSQL is the source of truth. Nothing here touches OpenSearch - the
-- index is rebuilt from these rows by reindexAll() on every connect, which is
-- also what repairs the index after Floci replaces the OpenSearch container.
--
-- Ids are <slugified-title>-<year>, matching httpapi.slugify so a row added
-- here and a movie created through POST /api/movies get identical treatment.

INSERT INTO movies (id, title, year, genre, director, synopsis, rating) VALUES
  ('the-shape-of-containers-2019', 'The Shape of Containers', 2019, 'Documentary', 'Ana Ruiz',
   'A crew of engineers packages an entire datacentre into a single laptop and learns what leaks out.', 7.8),
  ('namespace-1998', 'Namespace', 1998, 'Thriller', 'Piotr Nowak',
   'Two processes share a machine but cannot see each other. One of them starts leaving messages.', 8.1),
  ('the-privileged-2024', 'The Privileged', 2024, 'Drama', 'Marta Oliveira',
   'A container escapes its sandbox and discovers it was root on the node all along.', 7.2),
  ('cold-start-2021', 'Cold Start', 2021, 'Comedy', 'Dan Whitfield',
   'A function takes eleven seconds to wake up and the whole company waits.', 6.9),
  ('eventual-consistency-2016', 'Eventual Consistency', 2016, 'Romance', 'Yuki Tanaka',
   'They agreed on everything, just never at the same time.', 7.5),
  ('the-cache-invalidation-2012', 'The Cache Invalidation', 2012, 'Horror', 'Greta Lindqvist',
   'The data was correct. It was simply four hours old, and nobody noticed until the audit.', 8.4),
  ('fuzzy-match-2020', 'Fuzzy Match', 2020, 'Mystery', 'Samuel Adeyemi',
   'A search engine returns the right answer to a question nobody asked.', 7.0),
  ('port-forward-2023', 'Port Forward', 2023, 'Thriller', 'Claire Beaumont',
   'The only way into the cluster is a tunnel that closes every thirty seconds.', 6.6),
  ('split-brain-2015', 'Split Brain', 2015, 'Thriller', 'Hana Petrova',
   'Two nodes are both certain they are the leader. Both keep accepting writes.', 8.3),
  ('the-thundering-herd-2009', 'The Thundering Herd', 2009, 'Horror', 'Emeka Balogun',
   'Every cache entry expires at midnight. Every client wakes at the same moment.', 7.9),
  ('graceful-shutdown-2022', 'Graceful Shutdown', 2022, 'Drama', 'Lorna Vasquez',
   'Thirty seconds to finish what you started, and a queue that does not care.', 7.4),
  ('exponential-backoff-2018', 'Exponential Backoff', 2018, 'Romance', 'Tomas Herrera',
   'She said try again later. Then later. Then very much later.', 6.8),
  ('the-noisy-neighbour-2014', 'The Noisy Neighbour', 2014, 'Comedy', 'Ingrid Solberg',
   'Sharing a node with someone who compiles all night and never asks first.', 6.4),
  ('head-of-line-2011', 'Head of Line', 2011, 'Mystery', 'Dmitri Volkov',
   'First in the queue, perfectly healthy, and nothing behind it moves.', 7.1),
  ('immutable-2017', 'Immutable', 2017, 'Drama', 'Fatima Nasser',
   'A tag that was supposed to mean latest, and four teams who disagree about when.', 7.6),
  ('ambient-mesh-2025', 'Ambient Mesh', 2025, 'Thriller', 'Joon-ho Park',
   'Every packet is inspected by something nobody remembers installing.', 6.7),
  ('rollback-2013', 'Rollback', 2013, 'Documentary', 'Beatriz Cardoso',
   'An oral history of the migration that shipped without a down script.', 8.0),
  ('byzantine-2007', 'Byzantine', 2007, 'Mystery', 'Andrei Popescu',
   'A third of the generals were lying, and the messages all looked identical.', 8.6),
  ('write-amplification-2019', 'Write Amplification', 2019, 'Horror', 'Mei Lin Chao',
   'One small field update. Forty gigabytes of disk, and a pager at 3am.', 7.3),
  ('the-long-tail-2010', 'The Long Tail', 2010, 'Documentary', 'Oscar Delgado',
   'The median was fine. The story lives entirely in the last one percent.', 7.7),
  ('clock-skew-2006', 'Clock Skew', 2006, 'Mystery', 'Sofia Katsaros',
   'The events arrived in the wrong order, and one of them had not happened yet.', 8.2),
  ('blast-radius-2024', 'Blast Radius', 2024, 'Thriller', 'Nadia Farouk',
   'One configuration change, applied everywhere, correctly, in under four seconds.', 8.5),
  ('idempotent-2020', 'Idempotent', 2020, 'Comedy', 'Ruben Ortiz',
   'He proposed four times. She accepted once. The outcome was identical.', 7.2),
  ('the-straggler-2016', 'The Straggler', 2016, 'Drama', 'Aoife Brennan',
   'Ninety-nine workers finished. The batch is not done until the hundredth does.', 7.5),
  ('orphaned-2008', 'Orphaned', 2008, 'Horror', 'Viktor Almeida',
   'The parent exited cleanly. The children are still running, and still writing.', 7.8),
  ('backpressure-2022', 'Backpressure', 2022, 'Drama', 'Leila Haddad',
   'A system learns to say no upstream, and discovers nobody was listening.', 7.9),
  ('cardinality-2021', 'Cardinality', 2021, 'Mystery', 'Gustavo Pinto',
   'Somebody put a user id in a metric label. The dashboards have not recovered.', 7.0),
  ('the-retry-storm-2013', 'The Retry Storm', 2013, 'Horror', 'Karin Andersson',
   'Everyone tried again at exactly the same moment, and kept trying.', 8.1),
  ('cold-path-2018', 'Cold Path', 2018, 'Romance', 'Ismael Toure',
   'The query nobody ran for two years, on the morning it finally mattered.', 6.5),
  ('quorum-2005', 'Quorum', 2005, 'Drama', 'Elena Marchetti',
   'Three of the five had to agree. One was asleep and one had opinions.', 8.4),
  ('use-after-free-2011', 'Use After Free', 2011, 'Horror', 'Viktor Almeida',
   'The memory was returned. Something is still reading from it, and the answers keep changing.', 8.3),
  ('stop-the-world-2014', 'Stop The World', 2014, 'Drama', 'Mei Lin Chao',
   'Two hundred milliseconds where nothing happens, once a minute, forever.', 7.7),
  ('the-memory-leak-2003', 'The Memory Leak', 2003, 'Horror', 'Greta Lindqvist',
   'It grows by four kilobytes an hour. Nobody will notice for eleven months.', 7.4),
  ('zombie-2009', 'Zombie', 2009, 'Comedy', 'Dan Whitfield',
   'The process exited. Its entry in the table refuses to leave.', 6.6),
  ('the-oom-killer-2017', 'The OOM Killer', 2017, 'Thriller', 'Karin Andersson',
   'Something on this node has to die, and it will not be the thing that caused it.', 8.4),
  ('segmentation-fault-2001', 'Segmentation Fault', 2001, 'Mystery', 'Andrei Popescu',
   'Eleven, and no explanation. The core file is the only witness.', 7.9),
  ('thrashing-2004', 'Thrashing', 2004, 'Drama', 'Oscar Delgado',
   'Every page it needs was swapped out to make room for the pages it needs.', 7.2),
  ('fragmentation-2010', 'Fragmentation', 2010, 'Drama', 'Sofia Katsaros',
   'There is plenty of room. None of it is next to any other part of it.', 6.9),
  ('signal-handling-2012', 'Signal Handling', 2012, 'Thriller', 'Piotr Nowak',
   'Fifteen seconds to explain yourself before the second signal arrives.', 7.5),
  ('reaping-2015', 'Reaping', 2015, 'Horror', 'Emeka Balogun',
   'Nobody was assigned to collect the dead. They accumulate quietly.', 7.1),
  ('copy-on-write-2013', 'Copy On Write', 2013, 'Romance', 'Yuki Tanaka',
   'They shared everything until one of them changed a single page.', 7.6),
  ('the-page-cache-2007', 'The Page Cache', 2007, 'Documentary', 'Beatriz Cardoso',
   'How a machine convinces itself the disk is fast.', 7.3),
  ('cpu-steal-2019', 'CPU Steal', 2019, 'Mystery', 'Ingrid Solberg',
   'The graph says idle. The work is not getting done.', 6.8),
  ('inode-exhaustion-2006', 'Inode Exhaustion', 2006, 'Comedy', 'Ruben Ortiz',
   'Ninety percent free, and not one more file may be created.', 6.7),
  ('disk-full-2002', 'Disk Full', 2002, 'Horror', 'Claire Beaumont',
   'The logs recording the incident are what filled the volume.', 8.0),
  ('deadlock-2000', 'Deadlock', 2000, 'Thriller', 'Hana Petrova',
   'Each holds what the other needs. Neither will move first.', 8.5),
  ('race-condition-2008', 'Race Condition', 2008, 'Mystery', 'Dmitri Volkov',
   'It works every time it is watched, and fails when it is not.', 8.2),
  ('the-lost-update-2016', 'The Lost Update', 2016, 'Drama', 'Fatima Nasser',
   'Two writers, one row, and a change that was never there.', 7.4),
  ('optimistic-locking-2020', 'Optimistic Locking', 2020, 'Romance', 'Tomas Herrera',
   'He assumed nobody else would touch it. He was almost always right.', 7.0),
  ('lock-escalation-2011', 'Lock Escalation', 2011, 'Thriller', 'Nadia Farouk',
   'It only wanted one row. It took the whole table to be sure.', 7.3),
  ('priority-inversion-2005', 'Priority Inversion', 2005, 'Drama', 'Elena Marchetti',
   'The most important task waits behind the least important one.', 8.1),
  ('livelock-2018', 'Livelock', 2018, 'Comedy', 'Aoife Brennan',
   'Both of them keep politely stepping aside, forever, in the corridor.', 7.2),
  ('the-critical-section-2014', 'The Critical Section', 2014, 'Thriller', 'Joon-ho Park',
   'One at a time, and a queue that grows faster than it drains.', 7.6),
  ('spin-wait-2021', 'Spin Wait', 2021, 'Mystery', 'Gustavo Pinto',
   'It is doing nothing at full speed, and the fans know it.', 6.5),
  ('happens-before-2009', 'Happens Before', 2009, 'Mystery', 'Samuel Adeyemi',
   'Establishing what came first when the machines disagree about time.', 8.3),
  ('two-phase-commit-2004', 'Two Phase Commit', 2004, 'Thriller', 'Andrei Popescu',
   'Everyone voted yes. The coordinator went silent before it could tell them.', 8.6),
  ('the-saga-2019', 'The Saga', 2019, 'Drama', 'Marta Oliveira',
   'Six steps forward, and a compensating action for every one of them.', 7.8),
  ('vector-clock-2007', 'Vector Clock', 2007, 'Mystery', 'Sofia Katsaros',
   'Nobody agrees what time it is, only on what happened after what.', 8.0),
  ('gossip-2012', 'Gossip', 2012, 'Documentary', 'Ana Ruiz',
   'How a rumour reaches every node in a cluster, and how it stops.', 7.7),
  ('anti-entropy-2015', 'Anti Entropy', 2015, 'Drama', 'Lorna Vasquez',
   'Two replicas compare notes and find out how far apart they drifted.', 7.5),
  ('hinted-handoff-2013', 'Hinted Handoff', 2013, 'Romance', 'Ismael Toure',
   'It held the message for a node that might never come back.', 7.1),
  ('read-repair-2017', 'Read Repair', 2017, 'Mystery', 'Leila Haddad',
   'The answer was wrong, and asking fixed it for everyone after.', 7.4),
  ('leader-election-2010', 'Leader Election', 2010, 'Thriller', 'Hana Petrova',
   'Five candidates, one term, and a network that drops half the votes.', 8.4),
  ('log-compaction-2018', 'Log Compaction', 2018, 'Drama', 'Beatriz Cardoso',
   'Keeping only the last thing that was ever said about anything.', 7.0),
  ('the-witness-2016', 'The Witness', 2016, 'Mystery', 'Dmitri Volkov',
   'A third node that stores nothing and decides everything.', 8.1),
  ('replication-lag-2011', 'Replication Lag', 2011, 'Drama', 'Mei Lin Chao',
   'The read replica is nine seconds behind, and the user just refreshed.', 7.9),
  ('failover-2006', 'Failover', 2006, 'Thriller', 'Karin Andersson',
   'The standby took over. The primary never noticed it had stopped.', 8.2),
  ('partition-tolerance-2008', 'Partition Tolerance', 2008, 'Documentary', 'Oscar Delgado',
   'Pick two, they said, as if the network were offering a choice.', 8.5),
  ('linearizable-2022', 'Linearizable', 2022, 'Drama', 'Elena Marchetti',
   'Every operation appears to happen at one instant, and the cost is enormous.', 7.6),
  ('exactly-once-2020', 'Exactly Once', 2020, 'Comedy', 'Ruben Ortiz',
   'A support group for engineers who were promised something impossible.', 8.0),
  ('at-least-once-2014', 'At Least Once', 2014, 'Horror', 'Viktor Almeida',
   'The message arrived. It arrived again. It is still arriving.', 7.8),
  ('the-dead-letter-2009', 'The Dead Letter', 2009, 'Mystery', 'Claire Beaumont',
   'A queue nobody reads, holding every message the system could not understand.', 7.5),
  ('poison-message-2017', 'Poison Message', 2017, 'Horror', 'Emeka Balogun',
   'One malformed payload takes the consumer down, and it is redelivered on restart.', 8.1),
  ('consumer-rebalance-2021', 'Consumer Rebalance', 2021, 'Thriller', 'Joon-ho Park',
   'One member left the group. Everything stops while the partitions are redealt.', 7.3),
  ('watermark-2023', 'Watermark', 2023, 'Drama', 'Fatima Nasser',
   'Deciding when late is too late, and closing the window on the rest.', 7.2),
  ('phantom-read-2003', 'Phantom Read', 2003, 'Horror', 'Greta Lindqvist',
   'The row was not there the first time she looked. It has always been there.', 8.0),
  ('dirty-read-2005', 'Dirty Read', 2005, 'Thriller', 'Piotr Nowak',
   'She saw the value before he decided to keep it.', 7.4),
  ('serializable-2019', 'Serializable', 2019, 'Drama', 'Elena Marchetti',
   'Correct in every ordering, and slow enough that nobody chooses it.', 7.7),
  ('vacuum-2012', 'Vacuum', 2012, 'Documentary', 'Ana Ruiz',
   'The dead rows are still on disk. Somebody has to go and collect them.', 7.1),
  ('transaction-wraparound-2014', 'Transaction Wraparound', 2014, 'Horror', 'Andrei Popescu',
   'The counter is finite. In two hundred million transactions it stops accepting writes.', 8.3),
  ('sequential-scan-2007', 'Sequential Scan', 2007, 'Comedy', 'Dan Whitfield',
   'The index existed. The planner had its own ideas.', 7.0),
  ('the-query-plan-2016', 'The Query Plan', 2016, 'Mystery', 'Gustavo Pinto',
   'Same query, same data, and a completely different route through it every Tuesday.', 7.6),
  ('cardinality-estimate-2018', 'Cardinality Estimate', 2018, 'Drama', 'Sofia Katsaros',
   'It expected four rows and got nine million.', 7.5),
  ('n-plus-one-2013', 'N Plus One', 2013, 'Comedy', 'Ingrid Solberg',
   'One query to list them, and one more for each, four thousand times.', 7.3),
  ('connection-pool-2010', 'Connection Pool', 2010, 'Thriller', 'Nadia Farouk',
   'Twenty connections, two hundred requests, and a timeout that is too generous.', 7.8),
  ('the-write-ahead-log-2004', 'The Write Ahead Log', 2004, 'Documentary', 'Beatriz Cardoso',
   'Say what you are about to do before you do it, or lose the right to claim it happened.', 8.2),
  ('torn-write-2002', 'Torn Write', 2002, 'Horror', 'Karin Andersson',
   'Half the page made it to disk. The other half is from yesterday.', 8.4),
  ('fsync-2008', 'Fsync', 2008, 'Drama', 'Oscar Delgado',
   'The call returned. Whether the bytes are on the platter is a separate question.', 7.9),
  ('the-checkpoint-2011', 'The Checkpoint', 2011, 'Drama', 'Lorna Vasquez',
   'Everything before this line is safe. Everything after is a conversation.', 7.2),
  ('hot-partition-2020', 'Hot Partition', 2020, 'Thriller', 'Joon-ho Park',
   'Ninety percent of the traffic found the one shard that cannot take it.', 7.7),
  ('consistent-hashing-2015', 'Consistent Hashing', 2015, 'Documentary', 'Samuel Adeyemi',
   'Adding one node should move one node worth of data. Should.', 7.6),
  ('the-rebalance-2017', 'The Rebalance', 2017, 'Drama', 'Marta Oliveira',
   'Moving four terabytes while continuing to serve reads from it.', 7.4),
  ('tombstone-2009', 'Tombstone', 2009, 'Horror', 'Emeka Balogun',
   'The row was deleted. The marker saying so outlived the data by years.', 7.8),
  ('bloat-2006', 'Bloat', 2006, 'Comedy', 'Ruben Ortiz',
   'The table is eleven gigabytes. The data in it is four hundred megabytes.', 6.8),
  ('backfill-2021', 'Backfill', 2021, 'Drama', 'Aoife Brennan',
   'Rewriting six years of history without anyone noticing the present slow down.', 7.5),
  ('cache-stampede-2010', 'Cache Stampede', 2010, 'Horror', 'Hana Petrova',
   'One key expired. Nine thousand requests went to the database to rebuild it.', 8.2),
  ('negative-caching-2016', 'Negative Caching', 2016, 'Mystery', 'Dmitri Volkov',
   'It remembered the answer was no, long after the answer became yes.', 7.3),
  ('eviction-2013', 'Eviction', 2013, 'Drama', 'Fatima Nasser',
   'Something must go. The policy decides, and the policy has never been reviewed.', 7.1),
  ('least-recently-used-2005', 'Least Recently Used', 2005, 'Romance', 'Yuki Tanaka',
   'Forgetting whatever you have not thought about lately.', 7.4),
  ('the-bloom-filter-2018', 'The Bloom Filter', 2018, 'Mystery', 'Leila Haddad',
   'It can tell you no with certainty and yes only with confidence.', 7.9),
  ('sticky-session-2007', 'Sticky Session', 2007, 'Comedy', 'Claire Beaumont',
   'Every request must come back to the one server that remembers you.', 6.9),
  ('draining-2019', 'Draining', 2019, 'Drama', 'Ismael Toure',
   'No new connections. Just finish what is already in flight, slowly.', 7.2),
  ('certificate-expiry-2015', 'Certificate Expiry', 2015, 'Thriller', 'Viktor Almeida',
   'It was valid for ninety days and renewed automatically. Until it was not.', 8.5),
  ('the-handshake-2011', 'The Handshake', 2011, 'Romance', 'Tomas Herrera',
   'Six round trips to agree how to talk, before saying anything.', 7.0),
  ('split-horizon-2004', 'Split Horizon', 2004, 'Mystery', 'Mei Lin Chao',
   'The same name resolves to different machines depending on who is asking.', 7.6),
  ('dns-propagation-2001', 'DNS Propagation', 2001, 'Comedy', 'Ingrid Solberg',
   'It was changed hours ago. Somebody, somewhere, is still going to the old address.', 7.1),
  ('cascading-failure-2012', 'Cascading Failure', 2012, 'Horror', 'Nadia Farouk',
   'One slow dependency, and the timeouts were all set generously.', 8.7),
  ('the-circuit-breaker-2017', 'The Circuit Breaker', 2017, 'Thriller', 'Karin Andersson',
   'It stopped calling the failing service, and the failing service recovered.', 8.0),
  ('bulkhead-2020', 'Bulkhead', 2020, 'Drama', 'Elena Marchetti',
   'One compartment floods. The design decides whether the ship does.', 7.7),
  ('token-bucket-2014', 'Token Bucket', 2014, 'Comedy', 'Gustavo Pinto',
   'You may burst. You may not sustain. Nobody reads the second half.', 6.6),
  ('hedged-request-2022', 'Hedged Request', 2022, 'Thriller', 'Andrei Popescu',
   'Ask twice, take whichever answers first, and pay for both.', 7.5),
  ('tail-latency-2016', 'Tail Latency', 2016, 'Documentary', 'Oscar Delgado',
   'Everything is fast except the requests that matter to the loudest customer.', 8.1),
  ('jitter-2009', 'Jitter', 2009, 'Romance', 'Sofia Katsaros',
   'Everyone waits a slightly different amount, and that is what saves them.', 7.3),
  ('the-deadline-2023', 'The Deadline', 2023, 'Thriller', 'Joon-ho Park',
   'Every hop inherits what is left, and one of them did not get the memo.', 7.8),
  ('retry-budget-2021', 'Retry Budget', 2021, 'Drama', 'Beatriz Cardoso',
   'You may try again, but the system decides how often anyone may.', 7.4),
  ('crash-loop-2018', 'Crash Loop', 2018, 'Horror', 'Emeka Balogun',
   'It starts, it fails, it waits a little longer, and it starts again.', 8.3),
  ('the-canary-2015', 'The Canary', 2015, 'Thriller', 'Hana Petrova',
   'One percent of traffic, and the metric that would have caught it was not on the dashboard.', 8.0),
  ('blue-green-2012', 'Blue Green', 2012, 'Drama', 'Marta Oliveira',
   'Two identical environments, and a switch nobody has tested under load.', 7.4),
  ('rolling-update-2019', 'Rolling Update', 2019, 'Drama', 'Lorna Vasquez',
   'Both versions are live and they disagree about the schema.', 7.6),
  ('the-feature-flag-2017', 'The Feature Flag', 2017, 'Comedy', 'Dan Whitfield',
   'Temporary, added in March, still there four years later with three others depending on it.', 7.5),
  ('dual-write-2013', 'Dual Write', 2013, 'Horror', 'Claire Beaumont',
   'Two stores, one truth, and no transaction spanning them.', 8.1),
  ('shadow-traffic-2021', 'Shadow Traffic', 2021, 'Mystery', 'Samuel Adeyemi',
   'The new system sees every request and its answers go nowhere. Until they do.', 7.7),
  ('dark-launch-2020', 'Dark Launch', 2020, 'Thriller', 'Fatima Nasser',
   'It has been running in production for a month. Nobody outside the team knows.', 7.3),
  ('the-finalizer-2022', 'The Finalizer', 2022, 'Horror', 'Viktor Almeida',
   'The resource is marked for deletion. Something must confirm, and that something is gone.', 7.9),
  ('reconcile-2023', 'Reconcile', 2023, 'Drama', 'Ana Ruiz',
   'Compare what is to what should be, forever, and never assume you saw the change.', 8.2),
  ('drift-2016', 'Drift', 2016, 'Mystery', 'Dmitri Volkov',
   'The manifest says one thing. Somebody edited the cluster by hand in October.', 7.8),
  ('level-triggered-2014', 'Level Triggered', 2014, 'Documentary', 'Ismael Toure',
   'Why systems that look at state outlive systems that listen for events.', 7.6),
  ('the-admission-webhook-2024', 'The Admission Webhook', 2024, 'Thriller', 'Nadia Farouk',
   'Every pod must pass through it, and it has one replica.', 8.0),
  ('cordon-2011', 'Cordon', 2011, 'Drama', 'Aoife Brennan',
   'No new work here. The existing work does not know yet.', 7.0),
  ('preemption-2018', 'Preemption', 2018, 'Thriller', 'Joon-ho Park',
   'Something more important arrived, and your process was the cheapest thing to stop.', 7.5),
  ('disruption-budget-2020', 'Disruption Budget', 2020, 'Drama', 'Elena Marchetti',
   'How many may be down at once, agreed in advance, ignored during the incident.', 7.2),
  ('flapping-2009', 'Flapping', 2009, 'Comedy', 'Ruben Ortiz',
   'Scale up, scale down, scale up. The cooldown was set to zero.', 6.7),
  ('overcommit-2010', 'Overcommit', 2010, 'Thriller', 'Karin Andersson',
   'Everyone was promised more than exists. Most days that is fine.', 7.7),
  ('spot-interruption-2022', 'Spot Interruption', 2022, 'Horror', 'Mei Lin Chao',
   'Two minutes notice, and the checkpoint was written every five.', 7.9),
  ('cross-region-2019', 'Cross Region', 2019, 'Romance', 'Yuki Tanaka',
   'Ninety milliseconds apart, and every conversation pays for it twice.', 7.1),
  ('sampling-2017', 'Sampling', 2017, 'Mystery', 'Gustavo Pinto',
   'One trace in a thousand, and the interesting one was not kept.', 7.4),
  ('the-missing-span-2021', 'The Missing Span', 2021, 'Mystery', 'Sofia Katsaros',
   'The trace stops at a service boundary. Something did not pass the header.', 7.8),
  ('log-rotation-2005', 'Log Rotation', 2005, 'Comedy', 'Ingrid Solberg',
   'The evidence is compressed, archived, and deleted on a schedule nobody remembers setting.', 6.8),
  ('alert-fatigue-2016', 'Alert Fatigue', 2016, 'Drama', 'Oscar Delgado',
   'Four hundred pages this month, and the one that mattered looked like the others.', 8.4),
  ('the-runbook-2013', 'The Runbook', 2013, 'Documentary', 'Beatriz Cardoso',
   'Written after the last incident, for a system that has since been rewritten.', 7.6),
  ('blameless-2018', 'Blameless', 2018, 'Drama', 'Leila Haddad',
   'The postmortem asks how, not who, and it takes real discipline to keep it there.', 8.5),
  ('seccomp-2015', 'Seccomp', 2015, 'Thriller', 'Piotr Nowak',
   'A list of things it may ask the kernel, and one call that was not on it.', 7.7),
  ('capability-2012', 'Capability', 2012, 'Drama', 'Andrei Popescu',
   'Not all of root, only the specific piece of it that was needed.', 7.3),
  ('the-user-namespace-2020', 'The User Namespace', 2020, 'Mystery', 'Tomas Herrera',
   'Root inside, nobody outside, and a mapping that has to hold.', 7.9),
  ('chain-of-trust-2008', 'Chain of Trust', 2008, 'Thriller', 'Greta Lindqvist',
   'Every certificate signed by the next, up to one that signed itself.', 8.1),
  ('least-privilege-2014', 'Least Privilege', 2014, 'Drama', 'Hana Petrova',
   'Everything it needs and nothing more, decided by someone in a hurry.', 7.5),
  ('secret-rotation-2023', 'Secret Rotation', 2023, 'Thriller', 'Nadia Farouk',
   'Ninety days, automated, and three services that cached the old one at startup.', 8.0),
  ('supply-chain-2024', 'Supply Chain', 2024, 'Horror', 'Emeka Balogun',
   'Four hundred dependencies, and one of them changed hands last Tuesday.', 8.6),
  ('the-digest-2019', 'The Digest', 2019, 'Mystery', 'Marta Oliveira',
   'The tag moved. The digest is the only thing that ever meant this exact image.', 7.6),
  ('time-to-live-2007', 'Time To Live', 2007, 'Romance', 'Ismael Toure',
   'Everything here expires. The only question is whether anyone renews it.', 7.2)
ON CONFLICT (id) DO NOTHING;
